spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/safeshare_dp
    username: postgres
    password: motasem1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Make sure 'mail' is indented exactly 2 spaces, just like 'datasource' and 'jpa'
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: 48663b9cd59961
    password: b27e1908a37fad
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true